CREATE TABLE Users (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  FullName NVARCHAR(150) NOT NULL,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(500) NOT NULL,
  Role NVARCHAR(30) NOT NULL,
  AvatarUrl NVARCHAR(500) NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'active',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE InstructorProfiles (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
  Bio NVARCHAR(MAX) NULL,
  Expertise NVARCHAR(250) NULL,
  VerificationStatus NVARCHAR(30) NOT NULL DEFAULT 'pending',
  ApprovedAt DATETIME2 NULL,
  RejectedReason NVARCHAR(500) NULL,
  FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Categories (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Name NVARCHAR(100) NOT NULL,
  Slug NVARCHAR(120) NOT NULL UNIQUE,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Courses (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  InstructorId UNIQUEIDENTIFIER NOT NULL,
  CategoryId UNIQUEIDENTIFIER NOT NULL,
  Title NVARCHAR(200) NOT NULL,
  Slug NVARCHAR(220) NOT NULL UNIQUE,
  ShortDescription NVARCHAR(300) NULL,
  Description NVARCHAR(MAX) NOT NULL,
  Price DECIMAL(18,2) NOT NULL,
  DiscountPrice DECIMAL(18,2) NULL,
  ThumbnailUrl NVARCHAR(500) NULL,
  IntroVideoUrl NVARCHAR(500) NULL,
  Level NVARCHAR(50) NULL,
  Language NVARCHAR(50) NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'draft',
  RejectedReason NVARCHAR(500) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  PublishedAt DATETIME2 NULL,
  FOREIGN KEY (InstructorId) REFERENCES Users(Id),
  FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
);

CREATE TABLE CourseSections (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  CourseId UNIQUEIDENTIFIER NOT NULL,
  Title NVARCHAR(200) NOT NULL,
  SortOrder INT NOT NULL,
  FOREIGN KEY (CourseId) REFERENCES Courses(Id)
);

CREATE TABLE Lessons (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  SectionId UNIQUEIDENTIFIER NOT NULL,
  Title NVARCHAR(200) NOT NULL,
  VideoProvider NVARCHAR(50) NULL,
  VideoUrl NVARCHAR(500) NOT NULL,
  ThumbnailUrl NVARCHAR(500) NULL,
  DurationSeconds INT NOT NULL DEFAULT 0,
  IsPreview BIT NOT NULL DEFAULT 0,
  SortOrder INT NOT NULL,
  FOREIGN KEY (SectionId) REFERENCES CourseSections(Id)
);

CREATE TABLE Orders (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL,
  TotalAmount DECIMAL(18,2) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'pending',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE OrderItems (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  OrderId UNIQUEIDENTIFIER NOT NULL,
  CourseId UNIQUEIDENTIFIER NOT NULL,
  Price DECIMAL(18,2) NOT NULL,
  FOREIGN KEY (OrderId) REFERENCES Orders(Id),
  FOREIGN KEY (CourseId) REFERENCES Courses(Id)
);

CREATE TABLE Payments (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  OrderId UNIQUEIDENTIFIER NOT NULL,
  Provider NVARCHAR(50) NOT NULL,
  PaymentMethod NVARCHAR(50) NULL,
  ProviderTransactionId NVARCHAR(150) NULL,
  Amount DECIMAL(18,2) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'pending',
  RawResponseJson NVARCHAR(MAX) NULL,
  PaidAt DATETIME2 NULL,
  FOREIGN KEY (OrderId) REFERENCES Orders(Id)
);

CREATE TABLE Enrollments (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL,
  CourseId UNIQUEIDENTIFIER NOT NULL,
  OrderId UNIQUEIDENTIFIER NOT NULL,
  PaymentId UNIQUEIDENTIFIER NOT NULL,
  EnrolledAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (UserId) REFERENCES Users(Id),
  FOREIGN KEY (CourseId) REFERENCES Courses(Id),
  FOREIGN KEY (OrderId) REFERENCES Orders(Id),
  FOREIGN KEY (PaymentId) REFERENCES Payments(Id),
  CONSTRAINT UQ_Enrollment UNIQUE (UserId, CourseId)
);

CREATE TABLE LessonProgress (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL,
  LessonId UNIQUEIDENTIFIER NOT NULL,
  IsCompleted BIT NOT NULL DEFAULT 0,
  LastWatchedSecond INT NOT NULL DEFAULT 0,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (UserId) REFERENCES Users(Id),
  FOREIGN KEY (LessonId) REFERENCES Lessons(Id),
  CONSTRAINT UQ_LessonProgress UNIQUE (UserId, LessonId)
);

CREATE TABLE Reviews (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  UserId UNIQUEIDENTIFIER NOT NULL,
  CourseId UNIQUEIDENTIFIER NOT NULL,
  Rating INT NOT NULL,
  Comment NVARCHAR(1000) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY (UserId) REFERENCES Users(Id),
  FOREIGN KEY (CourseId) REFERENCES Courses(Id)
);
